Algoritmo "semnome"

Var
   placa:inteiro
Inicio
   escreva("Ultimo número da sua placa: ")
   leia(placa)
   se(placa=0)ou(placa=1)entao
   escreva("Não pode na segunda")
   fimse
   se(placa=2)ou(placa=3)entao
   escreva("Não pode na terça")
   fimse
   se(placa=4)ou(placa=5)entao
   escreva("Não pode na quarta")
   fimse
   se(placa=6)ou(placa=7)entao
   escreva("Não pode na quinta")
   fimse
   se(placa=8)ou(placa=9)entao
   escreva("Não pode na sexta")
   fimse

Fimalgoritmo